apiVersion: v1
kind: Secret
metadata:
    name: ledger-api-secrets
    namespace: payments
type: Opaque
stringData:
    STRIPE_API_KEY: ENC[AES256_GCM,data:HMP9DoxBiO442sJsyB/pbtal2Dqspfxw3htFm0s=,iv:K65JbLn+u8ammaP6zDHLdiS/DN24xIDzqo0l6g3xY2c=,tag:S24gwEozyQk2HKHRO4+k5A==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:qMdZYxfe8PIAvd0=,iv:cgb0QkIMwI/NnG7Y0J7Y4f5p3Mc/7cndhf7aboUUDvM=,tag:VaxNhVdO0rYrfy3QKlhe/g==,type:str]
    TOKEN_SALT: ENC[AES256_GCM,data:SbPRNESw6r10tzjNbBNqVRaS4EnlpHCqyHEH2++8UHM=,iv:RBM0Mzc4chZIcbIn10IDd7qw0dmc9zBzW61A1KUxiY4=,tag:Gae/OTUrx8c00HnCSFCE2Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5VE45ZmRuSy8raWdDTVBz
            MlZwbXkrR1dyOHhLVUJzbFNLRmxRb0t1WWh3CkxvdldKa1VwT3NpcVdWdmgyQ202
            eUlKN090QlB2bVFEVXUxTzVBalJaTUUKLS0tIGJvSndmakF4cXMxSk1HeXNhN3VY
            ZEZuOVdHcFJEMTdUeFFLM1NuNDFjYUEKbFxgTwfncpj5X4gBSlMuAsJCBH97059Q
            psSItWDm4fgvYTEqQAwYHN1vOWtUnw7fL02ou/+Km/GcChKTkS1UIA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h25e4f8dlwsqkjjlhdanag92jr55qgadeygrcadn06dgk8789g0sc528gt
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-29T07:40:51Z"
    mac: ENC[AES256_GCM,data:vkm3YJyKziNm+CjZJfiDI51uoWYgFywDxw3SSIQ0DLbbhmHabblfkJjN5yu7d3s6qyyA0ChUPVjYsWPO9SOxP+Mr2gkxeN96YNe05NHdEitY/TAkcA02jrSHdkSs1x35CFBFFz9eGPT7rilAojZfGyAdkVPJIka3DaTcYHbMUmI=,iv:Laz76cKnIYCYf4R9Wpxki6C6wyrpOrVKFyOyZsLt4uw=,tag:aopgjzSvmYvpfSNS6KwCQg==,type:str]
    version: 3.13.3
